{% set name = "mv_regex" %}
{% set version = "0.3.0" %}
{% set sha256 = "afa8cfafeaa41a0d3d22c2215234f6336754d8fccae9fff3515866ad8218920f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/mv_regex/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - mv_regex = mv_regex:main

requirements:
  host:
    - python >=3
    - pip
    - setuptools
  run:
    - python >=3
    - docopt
    - click

test:
  commands:
    - mv_regex --help

about:
  home: https://github.com/tdegeus/mv_regex
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Move files by applying an regular expression.
  description: Move files by applying an regular expression.
  doc_url: https://github.com/tdegeus/mv_regex
  dev_url: https://github.com/tdegeus/mv_regex

extra:
  recipe-maintainers:
    - tdegeus
